version: '3'
services:
  app:
    restart: always
    build: ./docker
    container_name: 'py-container'
    working_dir: '/var/docker-python' # Ambiguous understanding
    tty: true # What's this
    volumes:
      - ./app:/var/docker-python/app # Volume of source code
